Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -51,9 +51,9 @@ jobs:
         run: |
           ./vendor/bin/drush status || { echo "Drush cannot connect to the database."; exit 1; }
 
-      - name: Clear Drupal Cache
-        run: |
-          ./vendor/bin/drush cr || echo "Drush cache clear failed. Ensure the database and Drupal installation are ready."
+      #- name: Clear Drupal Cache
+      #  run: |
+      #    ./vendor/bin/drush cr || echo "Drush cache clear failed. Ensure the database and Drupal installation are ready."
 
       - name: Setup Node.js
         uses: actions/setup-node@v3
